baseurl = "http://xxxairinxxx.github.io/"
languageCode = "en-us"
title = "xxxAIRINxxx Site"
theme = "artists"

[params]

  name = "xxxAIRINxxx"
  description = "Your description"
  email = "xl1138@gmail.com"

  [params.header]
		title = "xxxAIRINxxx"
		shortBio = "iOS & Android Developer"

  [params.about]
  	title = "About me"
    bio = "iOS and Android Developer. State in Tokyo."

    [[params.about.skills]]
      name = "iOS"
      value = 8

    [[params.about.skills]]
      name = "Objective-C"
      value = 8

    [[params.about.skills]]
      name = "Swift"
      value = 5

    [[params.about.skills]]
      name = "Android"
      value = 3

    [[params.about.skills]]
      name = "Java"
      value = 3

    [[params.about.skills]]
      name = "Kotlin"
      value = 2

    [[params.about.skills]]
      name = "Node.js"
      value = 2

    [[params.about.skills]]
      name = "PHP"
      value = 2

    [[params.about.skills]]
      name = "Haskell"
      value = 1


  [params.work]
  	title = "Released My Apps"

  	[[params.work.projects]]
  		folder = "proj-1"

  	[[params.work.projects]]
  		folder = "proj-2"

  	[[params.work.projects]]
  		folder = "proj-3"

		[[params.work.projects]]
			folder = "proj-4"

  	[[params.work.projects]]
  		folder = "proj-5"

    [[params.work.projects]]
  		folder = "proj-6"

    [[params.work.projects]]
    	folder = "proj-7"

    [[params.work.projects]]
    	folder = "proj-8"

  [params.form]
    title = "Let's work together"
  	name = "Your Name"
    email = "Your Email"
    message = "Tell me"
    buttonText = "Send"

  [params.contact]
    title = "Contact"

    [[params.contact.social]]
  		icon = "github"
  		link = "//github.com/xxxAIRINxxx"
